### ISSUE TITLE
Audit zipcodes and their counties

### ISSUE THREAD

**Issue by jbreckman** [phoenixabs/zipcodes#2]
Zipcode 11249 seems to not have a statecode or county code.  I think this is because it's a new-ish zipcode.

There are lots of codes that don't have either, but I think they are mainly PO Boxes.  

We should fill in these gaps to make sure our data is uniform.  We can do this either manually or by finding a new data source to augment it.

**Comment by darogina** [comment]
Are we not able to update the sources in `scripts/fetch.sh` and then re-run `make fetch`?

**Comment by jbreckman** [comment]
those zipcodes aren't there.

https://www2.census.gov/geo/docs/maps-data/data/rel/zcta_county_rel_10.txt

I think this was published in 2010?  And they were introduced in 2011?

**Comment by darogina** [comment]
hmm. i'm assuming the most recent census data hasn't been released...

**Comment by jbreckman** [comment]
yeah i'm assuming it's not a huge number of zipcodes where there are gaps and we can just spot check them and fill them in
